name: Update Stats
on:
  schedule:
    - cron: '0 12 * * *' # Daily at 12PM UTC
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Update Cache Buster
        run: |
          sed -i "s/v=[0-9]*/v=$(date +%s)/" README.md
          git config user.name "GitHub Actions"
          git add README.md
          git commit -m "Update stats cache buster"
          git push
